{
    "prompt": "A car on the road",
    "negative_prompt": "low quality",
    "edit_prompt": "A yellow sportscar on the road",
    "src_img_path": "./data/imgs/A_car_on_the_road.png",
    "save_dir": "./pds_output/A_car_on_the_road",
    "loss_type": "pds",
    "guidance_scale": 7.5,
    "step": 500,
    "device": 0,
    "lr": 0.001,
    "log_step": 25,
    "precision": "fp32"
}